env = Environment(CPPPATH='/usr/include')

env.Program('SFMLApp', ['main.cpp',
                        'game.cpp',
                        'game_piece.cpp',
                        'input.cpp',
                        'gui.cpp',
                        'event_bus.cpp'],
            LIBS = ['sfml-window','sfml-system','sfml-graphics'],
            LIBPATH = ['/usr/lib', '/usr/local/lib'])
