env = Environment(CPPPATH='/usr/include',
                  CXXFLAGS="-g -std=c++0x")

env.Program('SFMLApp', ['main.cpp',
                        'game.cpp',
                        'event_handler.cpp',
                        'board.cpp',
                        'tile.cpp',
                        'piece.cpp'],
            LIBS = ['sfml-window','sfml-system','sfml-graphics'],
            LIBPATH = ['/usr/lib', '/usr/local/lib'])
